name: flutter_app_empty_template
description: "Flutter App Empty Template for Android, iOS, Web and Windows. This template is a starting point for a Flutter application."
publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_localized_locales: ^2.0.5
  go_router: ^12.1.1
  intl: ^0.18.1
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.5
  flutter_lints: ^2.0.0
  husky: ^0.1.6
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
